<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_DownloadTimeLimit
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
$data = $this->getDownloadableInfo();
$orderInfo = Mage::helper('downloadtimelimit')->getOrderInfo($data->getOrderIncrementId());
$customerData = Mage::getModel('customer/customer')->load($orderInfo->getCustomerId());
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo $this->__('Downloadable Information');?></h4></div>
    <fieldset>
        <table cellspacing="2" class="box-left">
            <tbody>
            <tr>
                <td><strong><?php echo $this->__('Product Name: ');?></strong></td>
                <td><?php echo $data->getProductName();?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Date created');?></strong></td>
                <td><?php echo Mage::helper('core')->formatDate($data->getCreatedAt(), 'full', false);?></td>
            </tr>
            </tbody>
        </table>
        <address class="box-right">
            <strong><?php echo $this->__('Customer Order');?></strong>
            <?php
            if($customerData){
                $name = $customerData->getName();
                $email = $customerData->getEmail();
            }else{
                $name = $orderInfo->getCustomerName();
                $email = $orderInfo->getCustomerEmail();
            }
            $group = Mage::helper('downloadtimelimit')->getCustomerGroupName($orderInfo->getCustomerGroupId());
            ?>
            <table cellspacing="0" class="form-list">
                <tbody>
                <tr>
                    <td class="label"><label>Customer Name</label></td>
                    <td>
                        <strong><?php echo $name;?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label>Email</label></td>
                    <td><a href="mailto:<?php echo $email;?>"><strong><?php echo $email;?></strong></a></td>
                </tr>
                <tr>
                    <td class="label"><label>Customer Group</label></td>
                    <td><strong><?php echo $group;?></strong></td>
                </tr>
                </tbody>
            </table>
        </address>
    </fieldset>
</div>